spring.application.name=gnosis-data-exportor
server.port=8090

spring.datasource.url=jdbc:opengauss://localserver.gnosis:5432/gnosis_sample?prepareThreshold=0
spring.datasource.username=gaussdb
spring.datasource.password=Enmotech@123
spring.datasource.driver-class-name=org.opengauss.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

springfox.documentation.swagger-ui.enabled=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB