DELETE FROM sys_data_mapping_test_case;
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_001', 'test_config_001', 'ERP_DIRECT_001', '正常合同数据映射-英文状态', 'TC_DIRECT_001', '{"contractData": {"contractNo": "HT2024001", "contractAmount": 1500000.567, "contractStatus": "ACTIVE"}}', '{"contractNo": "HT2024001", "amount": 1500000.57, "status": "ACTIVE"}', NULL, 0, NULL, '验证正常合同数据的字段映射和类型转换，英文状态直接保留', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_002', 'test_config_001', 'ERP_DIRECT_001', '中文状态映射测试', 'TC_DIRECT_002', '{"contractData": {"contractNo": "  ht2024002  ", "contractAmount": 2000000, "contractStatus": "生效"}}', '{"contractNo": "HT2024002", "amount": 2000000.00, "status": "ACTIVE"}', NULL, 0, NULL, '验证中文生效映射为ACTIVE，合同号trim+uppercase转换', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_006', 'test_config_001', 'ERP_DIRECT_001', '完成状态映射测试', 'TC_DIRECT_003', '{"contractData": {"contractNo": "HT2024003", "contractAmount": 500000.125, "contractStatus": "完成"}}', '{"contractNo": "HT2024003", "amount": 500000.13, "status": "COMPLETED"}', NULL, 0, NULL, '验证中文完成映射为COMPLETED', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_003', 'test_config_002', 'ERP_CROSS_002', '根节点到子节点映射', 'TC_CROSS_001', '{"contractNo": "  HT2024003  ", "contractAmount": 3000000.125}', '{"basicInfo": {"contractNo": "HT2024003"}, "paymentInfo": {"amount": 3000000.13}}', NULL, 0, NULL, '验证根节点字段映射到子节点，支持trim和四舍五入', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_004', 'test_config_003', 'ERP_CROSS_003', '子节点到根节点映射', 'TC_CROSS_002', '{"basicInfo": {"contractName": "测试合同"}, "paymentInfo": {"totalAmount": 5000.123}}', '{"contractName": "测试合同", "totalAmount": 5000.12}', NULL, 0, NULL, '验证子节点数据提取到根节点', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_005', 'test_config_003', 'ERP_CROSS_003', '多层级节点提取-四舍五入', 'TC_CROSS_003', '{"basicInfo": {"contractName": "多层级测试"}, "paymentInfo": {"totalAmount": 9999.999}}', '{"contractName": "多层级测试", "totalAmount": 10000.00}', NULL, 0, NULL, '验证多层级节点的数据提取和四舍五入进位', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_007', 'test_config_004', 'ERP_LIST_004', '数组提取和拼接', 'TC_LIST_001', '{"contractData": {"signatories": [{"partyName": "XX科技", "partyType": "甲方"}, {"partyName": "YY供应商", "partyType": "乙方"}]}}', '{"primaryParty": {"partyName": "XX科技", "partyType": "PRINCIPAL"}, "allPartyNames": "XX科技、YY供应商"}', NULL, 0, NULL, '验证按索引提取第一个签署方，并拼接所有签署方名称', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_data_mapping_test_case (id, config_id, config_code, case_name, case_code, request_json, expected_result_json, actual_result_json, is_passed, diff_info, description, status, create_user_id, update_user_id, create_time, update_time) VALUES ('tc_008', 'test_config_005', 'ERP_STRING_005', '字符串拆分和数据增强', 'TC_STRING_001', '{"contractData": {"partyNames": "XX科技,YY供应商"}}', '{"parties": [{"partyName": "XX科技", "partyType": "PRINCIPAL", "creditCode": "91110108MA1234567X"}, {"partyName": "YY供应商", "partyType": "VENDOR", "creditCode": "91110108MA7654321Y"}]}', NULL, 0, NULL, '验证字符串按逗号拆分，并通过静态数据源增强', 1, 'admin', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
