spring.application.name=liteflow-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localserver.gnosis:5432/gnosis_sample?currentSchema=gnosis_sample
spring.datasource.username=gaussdb
spring.datasource.password=Enmotech@123
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.gnosis.dynamic.liteflow.entity
mybatis.configuration.map-underscore-to-camel-case=true

liteflow.enable=true
liteflow.rule-source=classpath:liteflow-rule.xml

spring.sql.init.mode=never

logging.level.root=INFO
logging.level.com.gnosis.dynamic.liteflow=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
