spring.application.name=gnosis-datamapping
server.port=8086

# openGauss database
spring.datasource.url=jdbc:opengauss://localserver.gnosis:5432/gnosis_sample
spring.datasource.username=gaussdb
spring.datasource.password=Enmotech@123
spring.datasource.driver-class-name=org.opengauss.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/datamapping/*.xml
mybatis.type-aliases-package=com.gnosis.datamapping.domain
mybatis.configuration.map-underscore-to-camel-case=true

# Swagger
springfox.documentation.swagger-ui.enabled=true

# Initialize database schema and test data
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:db/datamapping/datamapping-opengauss.sql,classpath:db/datamapping/test-case-table.sql
spring.datasource.data=classpath:db/datamapping/test-data-init.sql,classpath:db/datamapping/test-case-data-init.sql
spring.datasource.sql-script-encoding=UTF-8

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
